fix: render the `uid` for all messages in a channel
asyncapi/markdown-template pull request #175
Opened 2021-10-04 06:10 UTC by stuartforrest-infinity

**Description**
Using the `markdown-template` renderer when a channel's subscribe/publish block has a single message associated with it the `uid` was not being rendered. This did not match the behaviour of the `html-tmplate` renderer. This PR resolves this inconsistency and will always render a message's `uid` regardless of how many messages there are.

**Related issue(s)**
Resolves #141

2021-10-04 06:13 UTC, stuartforrest-infinity commented
This is a tiny change and I've eyeballed the output is as expected when run against [this](https://github.com/asyncapi/generator/blob/master/test/docs/dummy.yml). The file being tested against as part of the `test:generation` npm job is an older version of this one, I'm not fully clear on the testing approach to the renders beyond the eyeballing the output but this may want updating?

2021-10-04 08:53 UTC, magicmatatjahu requested changes
Thanks for contribution @stuartforrest-infinity! Please refer to mu suggestion. When it comes to testing, don't worry, leave it as it is.

2021-10-04 08:53 UTC, magicmatatjahu commented on components/Channels.js
> +        <Message title={`Message \`${operation.message(0)}\``} message={operation.message(0)} />
Currently you render whole object and you end with output like:

```md
##### Message `[object Object]`

*This is just a dummy info message*

...
```

you should pass to the title `prop` only `uid` value like:

```suggestion
        <Message title={`Message \`${operation.message(0).uid()}\``} message={operation.message(0)} />
```

and then you will have:

```md
##### Message `dummyInfo`

...
```

2021-10-05 08:36 UTC, magicmatatjahu commented
@stuartforrest-infinity Ok, thanks for propagating my changes, however we have one last problem. Sometimes `message` can be empty, so we have to change the code for single message to the:

```js
      ) : operation.message(0) ? (
        <Message title={`Message \`${operation.message(0).uid()}\``} message={operation.message(0)} />
      ) : null}
```

to handle also case with empty message. Could you propagate it in your PR?

2021-10-05 09:11 UTC, stuartforrest-infinity commented
That is a little inconvenient. Your suggested change would change the output of the rendered because the current behaviour is even if there isn't a message a title should be rendered - https://github.com/asyncapi/markdown-template/blob/master/components/Message.js#L10.

To maintain the current behaviour I've pushed a change to conditionally render the `uid` instead if you can take a look.

I'm not sure the current behaviour makes sense but changing it is out of scope of this issue.

2021-10-05 09:23 UTC, magicmatatjahu commented
@stuartforrest-infinity If message doesn't exist, so for what render standalone `Message` title? For that I suggest to render message only when message object exists, so:

```js
      ) : operation.message(0) ? (
        <Message title={`Message \`${operation.message(0).uid()}\``} message={operation.message(0)} />
      ) : null}
```

is good.

2021-10-05 09:43 UTC, stuartforrest-infinity commented
Done :)

2021-10-05 09:47 UTC, stuartforrest-infinity commented
I'll do some refactoring to get rid of the nested ternary a bit later :)

2021-10-05 09:48 UTC, magicmatatjahu commented
@stuartforrest-infinity Yeah sure :) You can create separate component like below to avoid complex ternary operators:

```jsx
function Operation({ operation }) {
  const type = operation.isPublish() ? 'publish' : 'subscribe';
  return (
    <Text>
      <Header type={4}>{`\`${type}\` Operation`}</Header>
      {operation.summary() && (
        <Text newLines={2}>
          *{operation.summary()}*
        </Text>
      )}
      {operation.hasDescription() && (
        <Text newLines={2}>
          {operation.description()}
        </Text>
      )}
      <OperationMessage operation={operation} />
    </Text>
  );
}

function OperationMessage({ operation }) {
  if (operation.hasMultipleMessages()) {
    return (
      <>
        <Text newLines={2}>
          Accepts **one of** the following messages:
        </Text>
        {operation.messages().map(msg => (
          <Message title={`Message \`${msg.uid()}\``} message={msg} />
        ))}
      </>
    );
  }

  if (operation.message(0)) {
    return (
      <Message title={`Message \`${operation.message(0).uid()}\``} message={operation.message(0)} />
    );
  }

  return null;
}
```

Thanks!

2021-10-06 10:54 UTC, magicmatatjahu approved these changes
@stuartforrest-infinity Thanks for contribution! :)

2021-10-06 10:55 UTC, merged

2021-10-06 13:47 UTC, magicmatatjahu commented
@all-contributors please add @stuartforrest-infinity for bug, code